[2023-03-18 10:54:00,955] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag_v3.0.download_dataset_task backfill__2021-01-02T06:00:00+00:00 [queued]>
[2023-03-18 10:54:01,032] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag_v3.0.download_dataset_task backfill__2021-01-02T06:00:00+00:00 [queued]>
[2023-03-18 10:54:01,036] {taskinstance.py:1238} INFO -
--------------------------------------------------------------------------------
[2023-03-18 10:54:01,040] {taskinstance.py:1239} INFO - Starting attempt 6 of 7
[2023-03-18 10:54:01,043] {taskinstance.py:1240} INFO -
--------------------------------------------------------------------------------
[2023-03-18 10:54:01,101] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): download_dataset_task> on 2021-01-02 06:00:00+00:00
[2023-03-18 10:54:01,111] {standard_task_runner.py:52} INFO - Started process 5060 to run task
[2023-03-18 10:54:01,121] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag_v3.0', 'download_dataset_task', 'backfill__2021-01-02T06:00:00+00:00', '--job-id', '178', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp4jx4gtgy', '--error-file', '/tmp/tmp3cc8hfgc']
[2023-03-18 10:54:01,125] {standard_task_runner.py:77} INFO - Job 178: Subtask download_dataset_task
[2023-03-18 10:54:01,315] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag_v3.0.download_dataset_task backfill__2021-01-02T06:00:00+00:00 [running]> on host 8cface6de844
[2023-03-18 10:54:01,480] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-03-18 10:54:01,592] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag_v3.0
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2021-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=backfill__2021-01-02T06:00:00+00:00
[2023-03-18 10:54:23,034] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/operators/python.py:185 DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
[2023-03-18 10:54:29,989] {logging_mixin.py:109} INFO -    VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  trip_distance  RatecodeID  ... mta_tax  tip_amount  tolls_amount  improvement_surcharge  total_amount  congestion_surcharge
0       1.0  2021-01-01 00:30:10   2021-01-01 00:36:12              1.0            2.1         1.0  ...     0.5         0.0           0.0                    0.3          11.8                   2.5
1       1.0  2021-01-01 00:51:20   2021-01-01 00:52:19              1.0            0.2         1.0  ...     0.5         0.0           0.0                    0.3           4.3                   0.0

[2 rows x 18 columns]
[2023-03-18 10:54:30,021] {logging_mixin.py:109} INFO - columns: VendorID                        float64
tpep_pickup_datetime     datetime64[ns]
tpep_dropoff_datetime    datetime64[ns]
passenger_count                 float64
trip_distance                   float64
RatecodeID                      float64
store_and_fwd_flag               object
PULocationID                      int64
DOLocationID                      int64
payment_type                    float64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
dtype: object
[2023-03-18 10:54:30,025] {logging_mixin.py:109} INFO - rows: 1369765
[2023-03-18 10:54:49,756] {python.py:175} INFO - Done. Returned value was:          VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  trip_distance  RatecodeID  ... mta_tax  tip_amount  tolls_amount  improvement_surcharge  total_amount  congestion_surcharge
0             1.0  2021-01-01 00:30:10   2021-01-01 00:36:12              1.0           2.10         1.0  ...     0.5        0.00           0.0                    0.3         11.80                   2.5
1             1.0  2021-01-01 00:51:20   2021-01-01 00:52:19              1.0           0.20         1.0  ...     0.5        0.00           0.0                    0.3          4.30                   0.0
2             1.0  2021-01-01 00:43:30   2021-01-01 01:11:06              1.0          14.70         1.0  ...     0.5        8.65           0.0                    0.3         51.95                   0.0
3             1.0  2021-01-01 00:15:48   2021-01-01 00:31:01              0.0          10.60         1.0  ...     0.5        6.05           0.0                    0.3         36.35                   0.0
4             2.0  2021-01-01 00:31:49   2021-01-01 00:48:21              1.0           4.94         1.0  ...     0.5        4.06           0.0                    0.3         24.36                   2.5
...           ...                  ...                   ...              ...            ...         ...  ...     ...         ...           ...                    ...           ...                   ...
1369760       NaN  2021-01-25 08:32:04   2021-01-25 08:49:32              NaN           8.80         NaN  ...     0.5        0.00           0.0                    0.3         25.39                   0.0
1369761       NaN  2021-01-25 08:34:00   2021-01-25 09:04:00              NaN           5.86         NaN  ...     0.5        0.00           0.0                    0.3         30.22                   0.0
1369762       NaN  2021-01-25 08:37:00   2021-01-25 08:53:00              NaN           4.45         NaN  ...     0.5        0.00           0.0                    0.3         28.84                   0.0
1369763       NaN  2021-01-25 08:28:00   2021-01-25 08:50:00              NaN          10.04         NaN  ...     0.5        0.00           0.0                    0.3         31.79                   0.0
1369764       NaN  2021-01-25 08:38:00   2021-01-25 08:50:00              NaN           4.93         NaN  ...     0.5        0.00           0.0                    0.3         24.31                   0.0

[1369765 rows x 18 columns]
[2023-03-18 10:54:50,236] {xcom.py:334} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2023-03-18 10:54:50,245] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2141, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 100, in set
    value = XCom.serialize_value(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 331, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2023-03-18 10:54:50,350] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag_v3.0, task_id=download_dataset_task, execution_date=20210102T060000, start_date=20230318T105400, end_date=20230318T105450
[2023-03-18 10:54:50,559] {standard_task_runner.py:92} ERROR - Failed to execute job 178 for task download_dataset_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2141, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 100, in set
    value = XCom.serialize_value(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 331, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2023-03-18 10:54:51,333] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-03-18 10:54:51,570] {dagrun.py:628} WARNING - Failed to get task '<TaskInstance: data_ingestion_gcs_dag_v3.0.format_to_parquet_task backfill__2021-01-02T06:00:00+00:00 [removed]>' for dag 'data_ingestion_gcs_dag_v3.0'. Marking it as removed.
[2023-03-18 10:54:51,611] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-18 10:54:51,695] {dagrun.py:628} WARNING - Failed to get task '<TaskInstance: data_ingestion_gcs_dag_v3.0.format_to_parquet_task backfill__2021-01-02T06:00:00+00:00 [removed]>' for dag 'data_ingestion_gcs_dag_v3.0'. Marking it as removed.
