[2023-03-12 14:41:38,830] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_0 scheduled__2023-03-11T00:00:00+00:00 [queued]>
[2023-03-12 14:41:39,171] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: example_bash_operator.runme_0 scheduled__2023-03-11T00:00:00+00:00 [queued]>
[2023-03-12 14:41:39,187] {taskinstance.py:1238} INFO -
--------------------------------------------------------------------------------
[2023-03-12 14:41:39,192] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2023-03-12 14:41:39,195] {taskinstance.py:1240} INFO -
--------------------------------------------------------------------------------
[2023-03-12 14:41:39,607] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): runme_0> on 2023-03-11 00:00:00+00:00
[2023-03-12 14:41:39,665] {standard_task_runner.py:52} INFO - Started process 2157 to run task
[2023-03-12 14:41:39,787] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'example_bash_operator', 'runme_0', 'scheduled__2023-03-11T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', '/home/***/.local/lib/python3.7/site-packages/***/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpprcab84r', '--error-file', '/tmp/tmpdr71vx1r']
[2023-03-12 14:41:39,811] {standard_task_runner.py:77} INFO - Job 3: Subtask runme_0
[2023-03-12 14:41:40,934] {logging_mixin.py:109} INFO - Running <TaskInstance: example_bash_operator.runme_0 scheduled__2023-03-11T00:00:00+00:00 [running]> on host dc2eb824520f
[2023-03-12 14:41:47,256] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=runme_0
AIRFLOW_CTX_EXECUTION_DATE=2023-03-11T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-11T00:00:00+00:00
[2023-03-12 14:41:47,267] {subprocess.py:62} INFO - Tmp dir root location:
 /tmp
[2023-03-12 14:41:47,287] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "example_bash_operator__runme_0__20230311" && sleep 1']
[2023-03-12 14:41:47,459] {subprocess.py:85} INFO - Output:
[2023-03-12 14:41:48,428] {subprocess.py:89} INFO - example_bash_operator__runme_0__20230311
[2023-03-12 14:41:49,804] {subprocess.py:93} INFO - Command exited with return code 0
[2023-03-12 14:41:50,523] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=runme_0, execution_date=20230311T000000, start_date=20230312T144138, end_date=20230312T144150
[2023-03-12 14:41:50,982] {local_task_job.py:212} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-03-12 14:41:51,361] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 2157. PIDs of all processes in the group: [2157]
[2023-03-12 14:41:51,373] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 2157
[2023-03-12 14:41:51,379] {process_utils.py:70} INFO - Process psutil.Process(pid=2157, status='terminated', exitcode=0, started='14:41:38') (2157) terminated with exit code 0
